### ISSUE TITLE
Unable to use this `oauth` branch

### ISSUE THREAD

**Issue by crdant** [oktadeveloper/spring-boot-microservices-example#23]
I've been unable to use the code in the `oauth` branch without  adjustment. I was receiving an error with a page

```
<oauth>
  <error_description> Invalid token does not contain resource id (oauth2-resource</error_description>
  <error>access_denied</error> 
</oauth>
```

I fixed it by setting the `resourceId` explicitly in the code, using a value I put in `application.properties`. Submitted a PR with my code, not sure if there's a better way to do it, but it's how I got it working.

**Comment by mraible** [comment]
@crdant Did you follow the steps in [the tutorial](https://developer.okta.com/blog/2017/06/15/build-microservices-architecture-spring-boot) for this example? If you're using the same versions of libraries, and configured it for Okta, it should all work.

**Comment by mraible** [comment]
Please see https://github.com/oktadeveloper/java-microservices-examples for a more up-to-date example.
