### ISSUE TITLE
Could you please share the deploy.sh file for the windows box ?

### ISSUE THREAD

**Issue by JavaHelper** [oktadeveloper/spring-boot-microservices-example#3]
What is the sequence of the service starts ?

**Comment by mraible** [comment]
Unfortunately, I haven't written a version of deploy.sh that works on Windows. You can see the sequence of service starts in [run.sh](https://github.com/oktadeveloper/spring-boot-microservices-example/blob/master/run.sh). Basically, you need to start the Eureka service first, then everything else after that (order doesn't matter).
