### ISSUE TITLE
Homepage Stuck at "Loading..."

### ISSUE THREAD

**Issue by acs254** [oktadeveloper/spring-boot-microservices-example#4]
I updated baseUrl and clientId in okta.service.ts, and while everything builds fine, the homepage (http://localhost:4200/) is stuck at "Loading..." When I inspect the page, I see that there are 404 errors on the Okta CDN CSS and JS files (okta-sign-in.min.css, okta-theme.css, and okta-sign-in.min.js). Also, http://localhost:8081/login?next=%2Fhome loads fine.

I'm using Node 8.9.1.

**Comment by mraible** [comment]
That's weird that you see 404s. I'm able to run the example just fine. However, if you're using a recent version of Angular, [there is a bug](https://github.com/angular/zone.js/issues/891) when using `babel-polyfill` and `zone.js` that causes: `Uncaught TypeError: NativePromise.resolve is not a function`. To temporarily get around this issue, install an updated version of `zone.js`:

```
npm install https://github.com/lboyette-okta/zone.js.git#issue-891 --save
```

**Comment by acs254** [comment]
That solved the problem. Great catch. Were you just aware of that bug, or did you find it somehow?

**Comment by mraible** [comment]
I was aware of the bug, and it's noted in our documentation: https://developer.okta.com/code/angular/okta_angular_sign-in_widget.html
