### ISSUE TITLE
OAUTH_ERROR: 'redirect_uri' parameter

### ISSUE THREAD

**Issue by acs254** [oktadeveloper/spring-boot-microservices-example#5]
I'm encountering problems during login (http://localhost:4200), where I get the following error: "OAUTH_ERROR: The 'redirect_uri' parameter must be an absolute URI that is whitelisted in the client app settings." The result is an endlessly spinning wheel on the login page.

The following is a screenshot of what I see.

![screen shot 2017-11-27 at 11 33 57 pm](https://user-images.githubusercontent.com/5607218/33307553-c7b22c44-d3cb-11e7-9082-c9e4f28b1797.png)

I'm not entirely sure where I need to whitelist the URI. Any ideas?

**Comment by mraible** [comment]
Have you read the article that accompanies this repo? [Build a Microservices Architecture for Microbrews with Spring Boot ](https://developer.okta.com/blog/2017/06/15/build-microservices-architecture-spring-boot) is the name, and it links to [this article](https://developer.okta.com/blog/2017/06/13/add-authentication-angular-pwa.html), which has an [OIDC section](https://developer.okta.com/blog/2017/06/13/add-authentication-angular-pwa.html#create-an-openid-connect-app-for-angular) that tells you how to add a Redirect URI in Okta.

**Comment by mraible** [comment]
@acs254 You might have to add `http://localhost:4200` as a Trusted Origin under the API > Trusted Origins menu item.
